server:
  port: 80

spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
#    url: jdbc:hsqldb:hsql://localhost/jarvisdb
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      read-only: false
  jpa:
    hibernate:
      ddl-auto: create